import { Artist } from "../pages/lineup";

export const lineup: Record<string, Artist[]> = {
  Headliners: [
    {
      "ARTIST NAME": "Bayawaka",
      BIO: "Bayawaka is a chameleon, flawlessly adapting his colourful output to space and time. A Label DJ project a part of the Merkaba Music and Shanti Planti families, Bayawaka continues to develop a diverse library of psychedelic downtempo, bass music, breaks and electronica.\n\nA true vagabond of the festival circuit, Bayawaka consistently performs on the revered stages of Boom, Ozora, Mo:dem, Fusion, Rainbow Serpent, Origin and Tribal Gathering, along the way featuring at Universo Paralello, Glastonbury, Esoteric, Noisily, Hadra, Earth Frequency and Wild Horses. \n\nWith his ability to hold the floor from main stages to chillout zones alike, it's no wonder that the  world's biggest alternative music events have given Bayawaka their full support for the past decade.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://www.facebook.com/Bayawaka/ ",
      INSTAGRAM: "https://www.instagram.com/bayawaka.golanski/ ",
      SOUNDCLOUD: "https://soundcloud.com/djbayawaka ",
    },
    {
      "ARTIST NAME": "Golanski",
      BIO: "Golanski holds the flow steady, delivering deep, dark and hypnotic performances of progressive techno and trance. Bearing the title of Label DJ for Zenon Records and Digital Structures, Golanski explores these label's immense catalogues and beyond.\n\nBorn in Tel Aviv, the nomadic sonic warrior is now based in Berlin, though constantly driven to travel and express himself to the dancefloors of the globe. The Golanski project has featured at Ozora, Mo:dem, Universo Paralello, Fusion, Tribal Gathering, Esoteric, Earth Frequency, Rabbits Eat Lettuce, Wild Horses, Bucht Der Traumer and closed the famed Hammahalle main room at Sisyphos Berlin.\n\nA multi-disciplinary creative, Golan has founded boundary-pushing event platforms, catalyzed compilation releases for hallowed labels (including Digital Structures) and taken to the studios with Captain Hook, Mad Zach, Dekel and Gumi.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://www.facebook.com/DJGolanski ",
      INSTAGRAM: "https://www.instagram.com/bayawaka.golanski/ ",
      SOUNDCLOUD: "https://soundcloud.com/golanskidj ",
    },
    {
      "ARTIST NAME": "Terrafractyl",
      BIO: "Felix Greenlees, aka Terrafractyl, was raised on a diet of classical music, opera and jazz. Trained as a bassoon player, Felix worked for the Tasmanian and Melbourne Symphony Orchestras as well as freelancing for Opera Australia between 1999-2004.\n\nAt some point in the late 90s Felix had found his way to an outdoor goa trance party in Tasmania, was completely captivated by the psychedelic music he heard there and couldn't resist trying his hand at electronic music production. Since then, he has been weaving the threads of psytrance, jazz and classical music together, incorporating his love/addiction of piano and a new found addiction for building analog synthesizers. This unique melding of styles quickly led him to become one of Australia's most prominent electronic music performers.\n\nIn 2013 Felix established his own record label Kinematic Records, to help further his vision for psychedelic music, and for promoting and releasing music from many innovative and unique psychedelic musicians from Australia and around the world.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://www.facebook.com/Terrafractyl ",
      INSTAGRAM: "",
      SOUNDCLOUD: "https://soundcloud.com/terrafractyl",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Hypnagog",
      BIO: "Hypnagog is a musical project of Felix Fractal aka Terrafractyl and Mental Extensions.\n\nAfter years of writing Psychedelic dance music and experimenting with plenty of other sonic forms, Felix started to spend more time listening to downtempo, psychedelic breaks, IDM and the like. It was time to combine these styles with his own to create some kind of hybrid, beat driven, yet melodic sound. As the project has progressed, Felix has also been experimenting with a kind of jazzy progressive trance and has been working to combine these 2 styles into what could maybe be described as Psychedelic ProgStep. As always, his music is hard to describe and difficult to put into boxes and has been surprising and exhilarating audiences around the world for the past couple of years.\n\nHe has released two EP's on UP records , 'Dreaming in Pieces' (2009) and 'Gyroscopic Bebop'(2010) , and in 2012 another EP, 'Infinite Vibrations' on Adapted records. Most Recently, Felix released the debut Hypnagog album, 'Thematic Mathematics', on his own label Kinematic Records. This album represents the last 3 years of Felix's Hypnagogical experimentation, all wrapped up and woven into an intricate and very unique 80 minutes of sonic vibrations.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://www.facebook.com/Terrafractyl",
      INSTAGRAM: "",
      SOUNDCLOUD: "https://soundcloud.com/hypnagog",
      OTHER: "",
    },

    {
      "ARTIST NAME": "0dB",
      BIO: "Emerging from Cape Town and now rooted in the Central Coast of Australia, 0dB stands as a formidable DJ and producer signed to the reputable Furthur Progressions Records crew.\n\nHis journey through psytrance has seen him play his immersive soundscapes & rhythms across South Africa, England, Wales, Portugal, Indonesia, Thailand, and the unique terrains of Australia and New Zealand.\n\nHe has a growing portfolio of releases, seen in the company of esteemed figures such as Ninesense, Radikal Moodz, Oxyflux, Shadow Shaman, Dribble, Unexpected, Ace Ventura, Antix, Burn in Noise, Avalon, and more.\n\n0dB's unique sound palette is laden with groovy, nocturnal, and psychedelically soaked frequencies that are sonically charged with explosive energy. He looks forward to gracing our stage and taking us on a transcendent journey.\n",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://www.facebook.com/0db.psy",
      INSTAGRAM: "",
      SOUNDCLOUD: "https://soundcloud.com/0_db",
      OTHER: "",
    },

    {
      "ARTIST NAME": "Renegade DJ",
      BIO: "Hails from Cape Town, lived in London for 6 years, now living in Australia. Signed to legendary TIP Records. Her sets are full power psychedelic fullon. Each set is a meticulously crafted journey that keeps the dance floor energised and entertained, and her track selection is without fail always spot on for the time of day, venue and crowd. Her enthusiasm behind the decks and passion for the music is captivating and she never fails to impress - securing an ever-expanding fan base originating in Cape Town, reaching all corners of the world.\n\nSince migrating from the dance floor to the decks in 2009, she has played countless gigs in South Africa, the UK, Portugal, France, Germany, Turkey, Israel, the US, Indonesia, Thailand, Japan, Panama and New Zealand.\n\nHer most memorable performances include:\n\n- Noisily Festival 2014, 2015, 2016 | UK\n- Boom Festival 2014 | Portugal (Main Stage)\n- Fusion Festival 2016 | Germany (Trance Floor)\n- Ozora Festival 2016 | Hungary (Main Stage)\n- The Experience Festival 2017, 2019 | Thailand\n- Sunshine Festival 2018 | Japan\n- Tribal Gathering 2019 | Panama (Lotus Stage)\n- Dimension Festival 2023, 2024 | New Zealand (Main Stage)\n- Lost in Paradise NYE 2023 | New Zealand",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://www.facebook.com/RDJZero1",
      INSTAGRAM: "https://www.instagram.com/renegade_dj/ ",
      SOUNDCLOUD: "https://soundcloud.com/renegadedj ",
      OTHER: "",
    },

    {
      "ARTIST NAME": "Paris",
      BIO: "Attaining global audiences with millions of streams across releases on This Never Happened (USA), Stil Vor Talent (DE) and Of Leisure (AU) and having toured Europe, UK, India, USA and Mexico numerous times, Australia's PARIS is one of the country's most prolific electronic artists in her lane. With multiple Triple J and Double J high rotation radio ads and Spotify covers in the last two years to DJ spots on Australia's most in-demand festivals including Pitch Music Festival, Beyond The Valley and Splendour In The Grass, PARIS has paved her path.\n\nShe has garnered enthusiasts within the industry from Maceo Plex and Lane 8 to Joseph Capriati and Oliver Koletzki, while also commanding attention from Mixmag, Sirius XM and BBC Radio 1 with official remixes for Grammy winners RÜFÜS DU SOL, plus Cassian and Nils Hoffmann.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://www.facebook.com/parismusicau",
      INSTAGRAM:
        "https://open.spotify.com/artist/7ejF235eYuh8PlQDLaJy0N?si=1S2I-CAVQNSq-1rmcqULjw",
      OTHER: "https://www.abc.net.au/triplejunearthed/artist/paris-au/",
    },

    {
      "ARTIST NAME": "Hypertone",
      BIO: "The Hypertone Project expresses deep forest grooves and mysterious soundscapes. The music is fast paced (148-152bpm) and has a strong emphasis on entrancing, rhythmic and psychedelic elements, crafted specifically for melting night-time vibes.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://www.facebook.com/Hypertonetunes/",
      INSTAGRAM: "",
      SOUNDCLOUD: "https://soundcloud.com/rustone_offical",
      OTHER: "",
    },

    {
      "ARTIST NAME": "Grug",
      BIO: "'Grug', is the solo bass project of Sam Knights, co-founder/director of 8Ball Audio alongside Duos and Bustaflux. The Grug project focuses on a variety of deep electronic bass music influences combining styles  such as halftime, drum and bass, deep dubstep and left field bass.\n\nSince 2010, Sam has been playing an array of bass music styles under an assortment of alias's. Since performing as Sobek across Australia, NZ and the UK over many years, Sam has been focused on pushing his personal boundaries and providing versatile bass under 'Grug'.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://www.facebook.com/grugmusic",
      INSTAGRAM: "https://www.instagram.com/grugmusic/",
      SOUNDCLOUD: "https://soundcloud.com/grugmusic#/",
    },
    {
      "ARTIST NAME": "Audible Thought",
      BIO: "Playing mostly original productions including a healthy arsenal of unreleased tracks. Audible thought is known for his deep, chunky basslines infused with unmistakable grooves and captivating sound design.\n",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "https://soundcloud.com/audible_thought",
    },
    {
      "ARTIST NAME": "Lumos",
      BIO: "Imri Shavit, aka Lumos, is an artist who transforms light and motion into immersive experiences through real-time graphics and projection mapping. Starting his journey in Israel and expanding his craft across Australia, from Tasmania to Queensland, New South Wales, and Western Australia, Lumos creates visuals that pulse with energy, seamlessly connecting with the rhythm of the moment.\n\nTrue to the magic in his name, Lumos weaves dazzling displays of light that draw the dancefloor into a captivating vortex of visuals and sound. His work bridges the gap between technology and enchantment, inviting audiences on a journey that blurs the lines between reality and imagination.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "https://www.instagram.com/lumos.visuals",
      SOUNDCLOUD: "",
      OTHER: "",
    },
    {
      "ARTIST NAME": "VJ Lichenlight",
      BIO: "Lichen Light AKA Logan Wade (Loagsta) is a visionary VJ artist  with 12 years of experience in Southern Tasmania, Australia, specializing in stage design, projection mapping, and audiovisual synchronization. His transformative visuals and immersive environments have enchanted audiences at festivals and arts events. With meticulous attention to detail, Lichen Light seamlessly blends visuals to audio, creating a synchronous sensory harmony that elevates performances to new heights. His adaptability and versatility shine through in original artworks tailored to each stage or environment. By pushing the boundaries of visual storytelling, Lichen Light weaves luminescent tapestries that transcend imagination, transporting viewers to otherworldly realms. Prepare to be captivated by his cutting-edge techniques, innovative spirit, and profound artistic connection between sight and sound.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "https://www.instagram.com/loagsta_art",
      SOUNDCLOUD: "",
      OTHER: "",
    },
  ],
  AtoZ: [
    {
      "ARTIST NAME": "OGP",
      BIO: "OGP is a multi genre music selector, producer and appreciator based in nipaluna/Hobart. His interest in Electronic music started at an early age, and quickly realised he could generate sound using a computer. After experiments in music production, he eventually arrived in the world of Deejaying. Since 2015 he has been curating music for dance floors in lutruwita/Tasmania, ranging from House through Techno and into Trance. Having the technical ability to create a journey in any situation has enabled OGP to curate music for many different occasions. With advanced mixing skills and creative track selection, his setlists always lead to a solid dance floor. As a member of the collective 'Technobrats', he has been involved with a series of events, occasionally supporting interstate artists. \n\nAlso, as a regular in the club scene within lutruwita/Tasmania, OGP has had the opportunity to deejay at local venues such as 'Plan B' and 'The Grand Poobah'. In the outdoor scene, he has performed at events such as 'Fractangular Gathering' and other underground parties. Having practiced the craft of Deejaying for almost a decade, he is an experienced supporter of professional and amateur artists alike. With many successful sets under his belt, he is always a welcome addition to any line-up.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "https://www.mixcloud.com/the-ogp/",
      OTHER: "",
    },
    {
      "ARTIST NAME": "NFS",
      BIO: "NFS, or Nick Forbes-Smith, is a multitalented individual, equally at home behind a lighting desk as he is behind the decks. He refuses to be bound by genres. Expect a diverse range of music, everything from disco to breakbeat and atmospheric, mixed expertly.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "https://www.mixcloud.com/nickfs/",
      OTHER: "",
    },
    {
      "ARTIST NAME": "prog?na",
      imagePath: "/images/lineup/PROG_NA.png",
      BIO: "The psychedelic journey that awaits you when you step onto a prog?na dance floor is like no other, focusing more on the melodies rather than the basslines, \nprog?na will make sure you don't stop moving from the moment the fist tune start until the last song ends.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "https://on.soundcloud.com/tpdxm",
      OTHER: "",
    },
    {
      "ARTIST NAME": "psyDfx",
      BIO: "Julz aka psyDfx has been killing dancefloors for 13 odd years, but unlike Sophie Ellis-Baxter it's normally at ungodly hours in the morning and using secret recipes that he learnt from the trolls in Scandinavia (making it easier to hide the bodies).  \n\nAt multiverse he's doing something a bit different and bringing a selection of the freshest 2-step Garage, Dubsteps and Jungle straight from the warehouses and squats of Bristol and London.  Jungle so fresh it just swung off the vine with Tarzan",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD:
        "https://m.soundcloud.com/julian-wyatt-588518099?fbclid=IwAR0-_Y3477F5BYC8kNwvwgy18uAGwEhzRZnI-HOhuq4EsIWkdhJ6s9Lb-3o",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Kireesh",
      BIO: ' Kireesh ✺\n\nA multiplexing organized sonic attack,\nQuote, "keeping it groovy baby" personifies his approach towards all aspects of life not just his artistry.\n\nAlways with the intention of invoking a hypnotic trance within the listener and creating utopian spaces of healing through high bpms and intense psychedelia.\n\nLet\'s BLAST!!! :-)',
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "https://soundcloud.com/kireesh",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Spongeprog Psypants",
      BIO: "Emerging from a rainbow coloured, pineapple, under the sea. Spongeprog Psypants samples a range of wubs and psyices in order to flavour the ultimate Krabby Patty.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "Www.instagram.com/freekshow_",
      SOUNDCLOUD: "",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Psyora",
      BIO: "Psyora finds her inspiration from the dark and untouched depths of the forest. Heavily guided by her connection with nature, Nova aims to take listeners on a journey to a world outside of our own.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Vibrant Matters",
      BIO: "Vibrant Matters is an evolving musical project—new tracks emerging from older stems in fluid rhizomatic mutation. Blending hints of bush techno with organic instrumentation and soulful melodies, Vibrant Matters bends genres into a time-affected journey of influences and almost familiar echos. Each track is a living entity—unique yet interwoven—inviting listeners into a sonic ecology where all things may exist, and the act of seeking transforms what is found.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "https://vibrantmatters.bandcamp.com/",
    },
    {
      "ARTIST NAME": "StokeWizard",
      BIO: "StokeWizard hails from the mountain biking mecca of Derby, nestled in the northeast of Tasmania, and is currently expanding his reach in Queenstown, New Zealand. Since making his debut in the Tassie Doof scene in 2021, he has carved a niche for himself by bringing high-energy sets to unique events.\n\nFrom playing at world-renowned mountain biking events such as the Enduro World Series in Maydena and Derby to producing unforgettable afterparties for Red Bull Hardline 2024, Red Bull Crankworx Cairns 2024, and returning for RedBull Hard-line 2025. \nStokeWizard has proven his ability to unite audiences through sound.\nHis sets radiate a positive and incendiary energy, evolving with each performance as he refines his signature style. Expect nothing less than an electrifying journey through the sonic spectrum at Multiverse Festival.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "https://on.soundcloud.com/tXdB3GVfAcMUTnES7",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Raise the Ruth",
      BIO: "Ruth Degrassi, also known as Raise the Ruth, is a multi-talented female artist in the electronic music scene in Lutruwita/Tasmania.  Known for her unique blend and diverse range of organic and melodic house, techno, with classical influences and a splash of psychedelica, Ruth creates a sound that is danceable, inclusive and thought-provoking.\n\nRuth’s musical journey began at the age of 10, classically training as a vocalist, and as an adult performing in Lutruwita and on the mainland as a solo singer-songwriter for many years.  After falling in love with the doof scene and the dancefloor, she turned her attention to DJing, quickly developing a passion and honing her skills, playing at outdoor events on Country in Lutruwita.\n\nRuth’s live sets have been described as an immersive experience that takes the people on a journey, weaving a story and bringing the dance floor together with her uplifting frequencies and deeper soul sounds.  Her nostalgic, emotive and grounding music captures attention.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "https://www.mixcloud.com/ruth-merry-degrassi/",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Sean K",
      BIO: "Sean K \n\nElectronic music addict\n\nNipaluna/Hobart - TAS\n\nA master collector and intuitive selector, his passion for underground music transcends the ordinary to create immersive journeys that captivate the mind, body and spirit.\n\nSean thrives on the opportunity to pleasure his audiences through a series of intricate sounds, with a selection of Progressive, Minimal, Deep Tech, House & Techno. ",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "https://www.instagram.com/seankthedj/",
      SOUNDCLOUD: "",
      OTHER: "",
    },
    {
      "ARTIST NAME": "ZipperHead",
      BIO: "Welcome to the acid underworld of ZipperHead! \nBorn a bogan, became a gangster and found the psychedelics! BGP! \nFairly fresh meat for the scene of Tasmania but hitting all the marks with no bars held trance, hard tekno, and dark psy\nPlaying parties such as Phoenix Rising, Psy On Full Moon events and the Bris bang",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://on.soundcloud.com/VpNWAYCbupW1HLno9",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Psycars",
      BIO: "I’m Psycars—a twisted misfit. I normally mix fast psytrance or slow psychill. Weird, happy, and here to mess you up—come lose your mind with me on the chill stage at Multiverse 2025 <3",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://soundcloud.com/psycars",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Quantumpuss",
      BIO: "An alchemist of wonky bass, Quantumpuss explores a deep dichotomy of darkness and playfulness in every note, where the boundaries between the eerie and the mischievous blur in hypnotic fusion and sonic delight.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://on.soundcloud.com/nWoZjYzH3oHDGPibA",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Evangelo",
      BIO: "Hailing from the ancient city of Byblos, a musical maverick defying genre boundaries. His sets range from soulful house, to mind-bending psy-tech, designed to ignite the dance floor and soothe the soul",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://on.soundcloud.com/mhp2TaxVXypLoCyd7",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Nolsy",
      BIO: "Nolsy aka Niall only needs a few things to make him happy, icy cold beers, massive speakers and ultra thick bass chunks, expect a set full of everything from mid temp bass, funky tech house, drum and bass, garage, bass house and anything else that contains large throbbing bass lines, having played at the first multiverse he is very keen to blow the dance floor apart once again ",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://on.soundcloud.com/7bq2oVcnmzctSU896",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Eld",
      BIO: "Eld has been on a musical path since before he could walk, and as long as the heart keeps beating, so will the drum. Arriving in electronic music via the black roads of metal, he has maintained his taste for darker, deeper sounds—those that speak directly to your heart with undeniable force. Playful and determined, he invites you to move and be moved in the undercurrents.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://soundcloud.com/ninoxdesbois/memories-of-a-multiverse",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Kate Bain",
      BIO: "Kate Bain is a multi instrumentalist and genre defying dj, playing all sorts of music ranging from disco to techno. ",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Dr BoB",
      BIO: "\"Dr Bob aka Damien O'Brien is a collector. A collector of only the finest! Ranging from Funk, Prog , Bushtek, House, chill and all other forms of Art. All with a unique level of Dr BoB style funkiness. This time I am going to lay down some of the Funkiest Techiest Heavy House I can find.\n\n BASS MONKEY!\n\nBeen collecting and playing tunes 4 well over 20 yrs and been in the scene in some way or form since early 2000's. Starting in FNQ. \n\nCant Wait to See You all Shaking Your Tail Feathers on the D-Floor Soon 🐒\"",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://on.soundcloud.com/jXyZJ1QGE6464xrc6",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Staggersaur",
      BIO: "Staggersaur is a delicious hotpot of breakbeat, funk, and wobbly bass, cooked up by multi-instrumentalist Hayato. His sets are often marinated in narrative storytelling, seasoned with live hardware, and a garnished with a dash of violin. A rising name in the Australian electronic scene, you might have already spotted him in the wild at many festivals around Australia.\n",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "soundcloud.com/staggersaur",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Oracle and The Alchemist (Kari & Alice)",
      BIO: 'After many doof dreams pondering their musical collaboration, O & A played their first ever set together at Multiverse \'24. Over the hard thump of heavy techno, ethereal lyrics could be heard flowing through the forest as if sent from another realm; late night wanderers snuck through the trees to locate the sound. Liquid drum and bass poured into their beings as their souls were soothed by the sweet melodies and emotive spoken word.\n\nSinger Alice and DJ Kaedence curate an uplifting and soul-expanding union between rolling dnb breakbeats and sentimental lyrical content. \n\nYou are personally invited to join us in unity as we create this intuative musical experience as one feeling, seeing & healing entity. \n\nKaedence Bio:\n\n"Art decorates space - music decorates time."\n\nCadence:  \n1: a modulation or inflection of the voice.  \n2: a sequence of notes or chords comprising the close of a musical phrase.\n\nWelcome to the Kaedence frequency - we hope you enjoy your stay! \n\nOn this episode, we will remain true to form, while simultaneously testing the limits of new shapes, flavours and textures.\n\nExpect something along the lines of a "chill, uplifting, melodic, mixed bag of goodies - lucky dip style!"',
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "",
    },
    {
      "ARTIST NAME": "RoseTntd",
      BIO: "RoseTntd is the freeform bass music project of Atlanta Wessberg.\nA seasoned traverser of the aussie doof scene. RoseTntd was born through Atlanta's driving passion to bring more Bass music diversity and dubstep into Australia's outdoor music scene.\nFascinated by unique sound design and music that gets you skankin' n griming. RoseTintd's found her musical groove within the genres of dubstep,trap and experimental leftfield bass. \nHer passion and love for this music is reflected in her presence, performance and style! With the steeze to please and the beats to match RoseTntd won't be one to miss x 🌹\n",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "https://soundcloud.com/atlanta-wessberg/tracks",
    },
    {
      "ARTIST NAME": "Amattafact",
      BIO: "Known for his high-energy sets and hypnotic baselines, Amattafact always gets the crowd moving with his unique selection of DnB rollers. Originally hailing from QLD, Matt has been DJing for years,  exploring genres ranging from Bush Prog to Dub. Amattafact was born out of a deep love for DnB and the thriving Tasmanian Bass scene. Focusing on minimal, techy rollers, his sets traverse a range of DnB styles and are influenced by his love for hip hop and a diverse range of bass music. His passion for DJing is felt through every mix and his stripped-back, rhythmic blend of baselines are sure to get the crowd moving and keep them on the dance floor from start to finish. ",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Arunya Lee Olive",
      BIO: "Inspired by sounds of the underground, Arunya is an electronic music enthusiast hailing from nipaluna (Hobart), lutruwita (Tasmania). Selecting music that speaks to her soul, Arunya’s aim is to provide musical journeys through storytelling that inspire and energise individuals. Devoted to all things deep and hypnotic, Arunya always delivers an authentic and inspiring dancefloor experience.\n\nArunya has supported various artists from around the globe including:\nKlangkuenstler, Setaoc Mass, Peter Van Hoesen, SPFDJ, Schacke, ¥ØU$UK€ ¥UK1MAT$U, Luis M, 999999999, Mama Snake, Mha Iri, Claire Morgan, and Harvey McKay.\n\nArunya has also seen multiple headline slots across Tasmanian heavyweight festivals such as Dark Mofo many years running, Party In The Paddock and Mona Foma.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK:
        "https://www.facebook.com/profile.php?id=100064068189057&mibextid=wwXIfr&mibextid=wwXIfr",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "",
    },
    {
      "ARTIST NAME": "The Opporator",
      BIO: "Local Hobart DJ of 7+ years, loves mid / down tempo bass music, with a soft spot for anything hip hop / funk influenced. I’ll always intend to take the listeners on a journey through multiple tempo’s and vibes while blending those all together in a way similar to a live performance.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "https://on.soundcloud.com/3K3Yq4owAAfyVDKq7",
      OTHER: "",
    },
    {
      "ARTIST NAME": "ÜNAM",
      BIO: 'ÜNAM, a traveller & magic sound crafter who fuses electronic soundscapes with organic textures, deep melodies, big bass rhythms, and hypnotic sounds, all blended together through a strong solid and potent groove.\n\nHis sets embody the artistry of an alchemist, skillfully capturing the energy of the dancefloor and transmuting it into a powerful and uplifting experience. ÜNAM casts a spell on the crowd, creating a profound and unforgettable moment full of sensations and emotions that will leave them longing for an encore.\n\nHis releases on top international labels such as Bar25, House Music With Love, Cafe de Anatolia, BMG, Cosmic Awakenings, and LNDKHN have cemented his reputation in the global music scene.\n\nHe has performed and shared the lineup with notable artists such as Satori, El Buho, MoM, Joke, Betoko, WhoMadeWho, Goldcap, Monolink, Vintage Culture, Ali Farahani, Sainte Vie, Inellea, Seth Schwarz, Julya Karma,  Colyn, Dennis Cruz, S.I.S, Chancha Via Circuito.… and has played around the world in places like Ibiza, Tulum (Mexico), Miami(USA),  Goa (India), Los Angeles(USA), Dubai, Costa Rica, Mexico City, Russia, Turkey, Italy, Spain, Colombia, etc. \n\nPerforming in top venues and events around the world like Burning Man, Do Not Sit Miami, Giardino Dei Visionari, Fusion Festival Germany, Ozora Festival Hungary, Beachouse Ibiza, Sea Me Beach Turkey, La Pizzine, Azulik Tulum, Casa Reia Lisbon, Surf Club Dubai, EORA Cyprus, Raeeth Goa, Charka Russia, Red Bull KOA at Café del Mar, Nômade & Own Spirit Festival to name a few. All along with his talent landing him on Beatport\'s prestigious TOP 100 tracks lists lots of times.\n\nThough known for his signature organic electronic sound, ÜNAM’s versatility shines through in his ability to vary between deep, progressive, melodic, and higher BPM productions and DJ sets , always maintaining his own soundbrand. Whether delivering a more relaxed vibe or elevating the energy for a peak-time crowd, his unmistakable style and infectious groove make each performance unforgettable.\n\nAs the founder of ""The Magic Sun"" label, podcast and event brand, ÜNAM continues to explore and push the boundaries of his sound, offering both introspective journeys and energetic, floor-filling moments. His label is home to a vibrant community of international influential and emerging artists, carefully curated to reflect The Magic Sun’s ethos of creating immersive musical experiences. Through both the label and live events, ÜNAM fosters a global collective, bringing together music lovers and artists to connect through sound and shared experiences."',
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://www.facebook.com/UNAMbeat",
      INSTAGRAM: "https://www.instagram.com/unam.official/",
      SOUNDCLOUD: "https://soundcloud.com/unambeat",
      OTHER: "https://linktr.ee/unambeat",
    },
    {
      "ARTIST NAME": "FLOWYO",
      BIO: "FLOWYO\nRaised on a healthy diet of Chemical Brothers, Prodigy and Faithless, Yorick Fitzgerald has always had a passion for electronic music. Discovering doofing at the tender age of 15, becoming a dj was inevitable. Having performed under various monikers for two decades, including hosting and supporting many international artists as the founder of Thloop and co-founder of Project:01, FLOWYO is a resynthesis of parts, bringing all styles under one banner.\n\nFLOWYO's diverse and exacting tastes span a broad palette of genres, allowing him to craft unique journeys for any dancefloor. Whether sub rumbling bass music, groovy house vibes, uplifting tech progressions or grimy garage, FLOWYO's versatility ensures every set is a carefully curated experience reflecting a moment in time. ",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "https://mixcloud.com/flowyo",
    },
    {
      "ARTIST NAME": "Smoked Ham",
      BIO: "This slippery slice of smoked snackage, vindicated by a swarm of virtuous and valiant vegans, escaped the grips of butcher's hands and buttered bread to slide smoothly into a serendipitous slew of soulful sillybuggas and slapping sidetrance.\n\nTantalized by the titillating tempo and intricate tonality of Twilight, Ham began his detrimental descent into DJing with a focus on fast paced frequencies and manically manipulated melodies. He has since sunk his hoggy hooves into a more palatable platter of Progressive Psy, finding gratitude in groovy square wave bass lines accompanied by an array of analog arpeggiators and acidic attributes.",
      "ARTWORK COMPLETED": "Yes",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "https://on.soundcloud.com/VJG7LwPHPJ6L1iWa9",
    },
    {
      "ARTIST NAME": "Blip",
      BIO: "Curator of nocturnal journeys, blending aspects of both light & dark, expect blissful soundscapes & heaving basslines",
      "ARTWORK COMPLETED": "Yes",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "https://on.soundcloud.com/KzkGdwtko8uhD52o6",
    },
    {
      "ARTIST NAME": "RŸD",
      BIO: "RŸD is the new alias of Ryan Davenport. Based in Lutruwita/Tasmania RŸD is no stranger to club culture, starting off DJing at the young age of 17. \nHe has gone through many different sounds but has found himself being gravitated to the raw, hypnotic and groovy side of techno. \n\nRŸD is a stable in the underground scene in Tasmania and has played at many clubs and doofs around the state. His DJing style is extremely versatile and he is known for his ability to build a well stitched together journey throughout his sets.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "https://soundcloud.app.goo.gl/T5dQNkNRbuoUx4nv8",
    },
    {
      "ARTIST NAME": "MINITECELEC",
      imagePath: "/images/lineup/placeholder.png",
      BIO: "Minimal as",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "",
    },
    {
      "ARTIST NAME": "INDI",
      BIO: "Born in Tasmania and now calling the Sunshine Coast home, INDI has built a passion for electronic music, nightlife and raves for the past 15 years. In 2019, INDI attended her first bush doof in Tasmania where dancing in nature, connecting and play sparked her true love for the scene. It was this connection that inspired her to learn to mix herself and one day be able to play at one of these bush parties she loves so much. That dream has come to life with her performance at Multiverse—a significant milestone for the aspiring DJ.\n",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "https://on.soundcloud.com/YzLNoqXTa7DBgDpd7",
    },
    {
      "ARTIST NAME": "Taz Az",
      BIO: "Taz Az is Psychedelic DJ project of Aaron Purton\nComing from the central Tasmanian region he has been mixing various styles at some outdoor gatherings in Tasmania for just over 6 years now and has been slowly finessing his way of mixing music in this time. He generally plays Psytrance, but tends to like to get on the mixer and have a go with any good music! 👽",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "https://on.soundcloud.com/GQJVZmH9DW16MfVeA",
    },
    {
      "ARTIST NAME": "Firefly and Geometry",
      BIO: "Firefly and Geometry are a DJ duo whose partnership extends beyond the decks—these two\nare partners in life, love, and music. Blending their individual styles into an experience,\nthey’ve become known for their unique events that celebrate everything from hip hop to\ncommercial hits.\n\nFirefly is the free spirit of the pair, a fire spinner and creative soul who brings passion to their\nperformances. Geometry, the grounded counterpart, keeps the beats sharp and the mixes\nsmooth. Together, their chemistry is undeniable.\n\nWith Firefly's vibrant presence and Geometry's steady precision, they draw in the crowd and\nkeep the vibe alive all night, because their energy is infectious. Firefly and Geometry are a\nforce to be reckoned with on and off the stage",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://www.facebook.com/share/1G4um898WN/?mibextid=wwXIfr",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Arddhu",
      BIO: "Atmospheric jungle to tickle your brain pickle. Into the 90's... into the 90's... into the 90's... and beyond. Keep it locked. ",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "https://soundcloud.com/arddhu",
    },
    {
      "ARTIST NAME": "fy_niceworld",
      BIO: "fy_niceworld is the production half of alt-pop duo ALTA, returning to the stage after a four-year hiatus. Blending garage and DnB, their set at Multiverse marks a return to the dance floor.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Everest Premium",
      BIO: "Come with me now, on a journey through time and space. A voyage from darkness into light as we meet the sunrise with my favourite quirky, groovy and cheeky tunes",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "https://www.instagram.com/jocelyn_parry_jones/",
      SOUNDCLOUD: "https://soundcloud.com/jocelyn-parry-jones",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Shearwater",
      BIO: "Inspired by travelling to hear music from all over the world, Shearwater takes you on a tribal-like migration across the globe and through time.  Described as an Eco-Mystic, nature and culture are at the forefront of Shearwater’s sets.  Take a flight through the environs of sound, dusky-light and grinding-dark, ancient acoustic electronica, with beauty and bass.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "https://soundcloud.com/treat-tribe",
    },
    {
      "ARTIST NAME": "Siren Hunt",
      BIO: "Siren Hunt weaves middle eastern downtempo electronica to lure you to the dance floor for sensuous tunes and sweet dance. ",
      "ARTWORK COMPLETED": "Yes",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "https://www.kattraill.com",
    },

    {
      "ARTIST NAME": "Kate Kate",
      BIO: "Artist bios are not her forte but psychedelic techno is. As a dance floor introvert herself, Kate Kate favours the dark, driving, hypnotic sounds of techno and psy and invites her audience to lose themselves in the beat.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "https://mixcloud.com/katekate8",
    },
    {
      "ARTIST NAME": "Facula",
      BIO: "Facula is a seasoned psytrance DJ and producer, deeply rooted in the northern New South Wales psytrance culture. For many years, he has crafted immersive soundscapes that blend the natural world with electronic rhythms. Known for his seamless fusion of nature-inspired sound design, rhythmic percussion, and smooth, flowing melodies, Facula creates sonic journeys that resonate both on the dance floor and in the wild.\n\nHaving performed on stages across the east coast of Australia, Facula has shared the spotlight with some of the scene’s most respected names, including Pspiralife, Grouch, Melt, and Ryanosaurus. His dynamic live sets channel the energy of his surroundings, building atmospheric soundscapes that captivate listeners and transport them to ethereal realms.\n\nFacula continues to evolve his sound, drawing inspiration from the world around him while pushing the boundaries of psytrance with each new performance.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "https://on.soundcloud.com/27F2VJu4cpNpueWW7",
    },
    {
      "ARTIST NAME": "Jazzle",
      BIO: "Journey into the psychedelic realms of Jazzle's mind where musical frequency's dance and play.\n\nFocusing on deep earthy soundscapes and swampy vibes, while finding synergy between light and dark.\n\nLover of all genres of Psychedelic Trance though focusing on the Bush and Dark Progressive sound.\n\nJazzle has played at some iconic underground Tasmanian festivals such as Repulse, Multiverse, Honeypot, Spored, Pheonix Rising and Cosmic Portal.",
      "ARTWORK COMPLETED": "Yes",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "https://soundcloud.com/jazzle_tas",
    },
    {
      "ARTIST NAME": "Chief Get Down",
      BIO: "If you crave the funk, and desire a stage presence so loud you'll have no choice but to throw down like Charlie Brown, then get yourself a dose of Chief Get Down. With a tight selection of fun and groovy tech-house and glitch, among other dance-floor delights, this curator of elation truly lives up to his reputation.",
      "ARTWORK COMPLETED": "Yes",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "https://soundcloud.com/chiefgetdown",
    },
    {
      "ARTIST NAME": "Clay Crosier",
      BIO: "Clay Crosier is a constant across the Tassie music scene. He is a resident DJ and core part of SPICYMUSIC and has performed at an array of underground parties and festivals all over Tassie, such as Junction Arts Festival, Party in the Paddock, Multiverse and Synergy Festival to name a few.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "https://soundcloud.com/claycrosiermusic",
    },
    {
      "ARTIST NAME": "Macca",
      BIO: "Macca plays a range of worldly music, with an unforge mix of beats, tempos and, rythms.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "",
    },

    {
      "ARTIST NAME": "Koshiro",
      BIO: 'Oscar started his musical journey in 2014 dabbling in the realms of digital music production. Only to later form Perspective in 2016, whereby continuing to pave the way for a new wave of sonic explorations. This project "Koshiro" was birthed in 2020 and has captivated listeners since. Born out of a labour of love, Koshiro has been striving to take listeners on a transformative journey with pulsating square basslines, hypnotic rhythms, and funky groovadelic acid leads.\n\nInspired by his love for Japanese culture, Koshiro embarked on a journey to create a unique and groundbreaking style of deep psychedelic trance that would push the boundaries of electronic music. With a desire to break new ground, Koshiro merges the melodic and atmospheric elements of Deep House with the driving energy and the psychedelic intricate textures of PsyTrance. Koshiro\'s commitment to pushing the boundaries of musical genres is evident in his ability to seamlessly blend contrasting elements.',
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://www.facebook.com/KoshiroPsy",
      INSTAGRAM: "",
      SOUNDCLOUD: "https://soundcloud.com/koshiropsy",
      OTHER: "",
    },

    {
      "ARTIST NAME": "Alterpath",
      BIO: "Alterpath is a duo made up of Sam Sanderson and Bai Sumeng based in Tasmania Australia. They've been making music for 12 years, originally creating dubstep and now branching out into house, garage, UK grime, trap and latin based production. Alterpath leave no stone unturned in exploring sonic aesthetics to build up their repertoire. Sam Sanderson started writing music in 2011 when he was 13. Inspired by the likes of Skrillex, Zomboy and Space Laces, he loved heavy dubstep and spent his first years learning sound design and music theory. Bai Sumeng joined the duo in 2020 when they bonded over their love for music and edm. Having played numerous festivals, bush doofs and headline shows, Alterpath are beginning to spread their sound all across Australia.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "https://on.soundcloud.com/LoDcnJ8HqAZWTBpV6",
      OTHER:
        "https://open.spotify.com/album/4qBFipawv4W9xnQpab4G8d?si=vlv-Asm9RRurq-VAPgah-g&nd=1&fbclid=IwY2xjawHmR8NleHRuA2FlbQIxMAABHbIA51u7zDxLmPItNc3m4V7POn2l7ijBc2oGQSOdZ2rx6SamylYWs1jYAw_aem_1W2zeNbsDHXZ4PItBG2_0Q&_branch_match_id=1404133728022736935&utm_medium=sharing&_branch_referrer=H4sIAAAAAAAAAw3LzQ6CIAAA4LfpmEk%2FtjbXMFe6zDK3Si8MDAoDdaBDPfTs9d2%2Fd9s2emNZuqlbzoap4NXHmrNjxGWMdwPZMlII%2FnRDk4G%2BxCaQ13UsaHDtINgLkoT9CUIvICFc2p0z%2Bn0kL2EbF3O5uDmXcwWEw0uvAPUhSc%2FPHKh%2BlWI5iOyu7TKDBmEqkX0HI42J9oNHvvh37wDQLJl8FWVUKV69EFG10VS5KWZY8R9%2FWxsftQAAAA%3D%3D",
    },
    {
      "ARTIST NAME": "Billy Bones",
      BIO: "",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Finch",
      BIO: "Finch has been an active part of the Australian dance scene for over 15 years, actively DJing and promoting in the southern island of Tasmania. He has held several residencies, including lounge bars and nightclubs, and has played at events and festivals in Hobart and around Australia. Finch has had the flexibility and talent to support a long list of touring DJs, from the best in Australia (Kid Kenobi, Aston Shuffle, Yolanda Be Cool) to around the world (Roger Sanchez, Thomas Schumacher, Wolfgang Gartner, Fedde Le Grand, Patrick Topping and many more). Finch has incredible versatility and groove, with sounds ranging from underground techno and house, deep tech, to funk, soul & disco. \n\nIn 2016 he co-founded a renegade dance collective called Technobrats, with a focus on local talent, custom lighting, and unique locations. Now into its 8th year of operations, Technobrats have built an underground following for high-quality events, including Multiverse, a 4 day camping music festival held each January.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "https://www.instagram.com/alterpathmusic/",
      SOUNDCLOUD: "https://soundcloud.com/finch",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Fotti P",
      BIO: "Some music you hear and some music you feel. Fotti P's enthusiastic style draws you in with a hypnotising beat that will get you swaying from the heart and stomping your feet. His infectious sounds span the gamut of disco, house and techno with a strong dose of baseline.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://www.facebook.com/djfottip",
      INSTAGRAM: "",
      SOUNDCLOUD: "https://soundcloud.com/fottip",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Guinplex",
      BIO: "Guinplex is a Forest project undertaken by Peter Kokavesis, a DJ and producer who enjoys high BPM music and loitering on the outskirts of the dancefloor.\n\nHaving played at local parties for a small while around Tasmania, Guinplex has cemented himself as a reputable night-psy act with his Forest sets best described as dark, ritualistic and purely psychedelic.\n\nGuinplex is currently 5 years into undertaking his own journey into production and has already started testing his original work on Tassie dancefloors.\n\nIf it's dark, driving and trance-inducing music you're looking for, Guinplex is not one to miss out on!",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "https://www.soundcloud.com/guinplex",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Gÿps & Spice",
      BIO: "Gÿps & Spice are a techno duo from lutruwita (Tasmania) who have been at the forefront of the underground music scene in lutruwita since 2013. Gÿps & Spice are the founders & residents of lutruwita's leading techno movement SPICYMUSIC, which has been running parties & raves since 2015, featuring International & local DJs and Producers. \n\nTheir style has been labeled as groovy & energetic, psychedelic & tribal. Their sets are best known to have a push and pull between hard & fast, sexy & trippy driven sounds, interwoven with tribal groove, a touch of 90s rave and hip-hop vocal influences.\nThe energy in their sets has a lasting, positive effect on others. \n\nAs a duo, they have been headliners at events such as Dark Mofo 2024 and In The Hanging Garden in Tasmania, and interstate at Goodbar & WeLove in Sydney. They perform regularly at club nights & festivals throughout lutruwita along with being invited to perform in other Australian cities for techno nights & festivals such as Babylon Festival in naarm (Melb), Junction Arts Festival, Great Escape Festival, Multiverse Festival, Synergy Festival, & Revel all in lutruwita (Tas).\n\nThey have played main support alongside some of the major techno artists across the globe, such as Setaoc Mass, Peter Van Hoesen, SPFDJ, Henning Baer, Amelie Lens, Charlotte de Witte, Anetha, Perc, Dasha Rush, Bart Skils, Farrago, Boris Of Berlin, Wehbba, Luigi Madonna, Enrico Sangiuliano, Secret Cinema, Arjun Vagale, Pig&Dan, & Mark Reeve among others.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://www.facebook.com/SPICYMUSICTAS",
      INSTAGRAM: "https://www.instagram.com/spicymusic_tas/",
      SOUNDCLOUD: "https://soundcloud.com/gypsydj",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Kaedence",
      BIO: '"Art decorates space - music decorates time."\n\nCadence:  \n1: a modulation or inflection of the voice.  \n2: a sequence of notes or chords comprising the close of a musical phrase.\n\nWelcome to the Kaedence frequency - we hope you enjoy your stay! \n\nOn this episode, we will remain true to form, while simultaneously testing the limits of new shapes, flavours and textures.\n\nExpect something along the lines of a "chill, uplifting, melodic, mixed bag of goodies - lucky dip style!"',
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "https://on.soundcloud.com/K8vkQWwVBFep6nLi9",
      OTHER: "https://www.mixcloud.com/Kaedense",
    },
    {
      "ARTIST NAME": "Liminality",
      BIO: "Liminality is defined as the feeling of ambiguity and disorientation felt during the middle stage of a transition. \n\nIn the case of Hobart based Liminality, this describes the bittersweet feeling similar to nostalgia felt while flying, travelling or reflecting on the past and/or future. \n\nLiminality's genre bending music tries to recreate these powerful feelings with dream-like atmospheric breakdowns combined with fresh, complex drops ranging from dark and distorted (ft elements from Garage and dubstep) to tight, twitchy and melodic (ft elements from IDM and future bass) and even ethereal, harmonic rich and ambient (ft elements from Downtempo and Electronica). \n\nLiminality's influences include Jon Hopkins, Mr Bill, Bonobo, Koan Sound and Deadmau5.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "https://www.instagram.com/liminality.music/",
      SOUNDCLOUD: "",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Morphlink",
      BIO: '"To morph into something that my mind set to.."  \n\n"To link earthlings through music.."  \n\nSelf-taught mixer who loves to share her journey of experiencing melody, waves, and rhythm. Delivering a smorgasbord of melody, percussion, and beats from the various range of genres. \n\nCaptivating the hearts and minds, she leads them on a journey to experience darkness, light, and everything in between. Surrounding this spectrum is a silver lining of nostalgic favourites and all-time classics.\n\nShe is on a mission to heal all beings through the power of frequencies in the form of beats that can tingle your cells.',
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "https://soundcloud.com/morphlink",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Rosemary",
      BIO: "‘Rosemary’ is a Tasmanian based artist and ecologist, inspired by numerous forms of expression and challenge…or potentially just too distracted to focus on one thing.\n\nWhen not at his day job, counting fish, you’ll find him mixing bass-laden sets at bush doofs, both within Tassie and farther afield on the big rock. With an ear for many sounds, his sets encompass a range of genres and pace, he likes to get you moving at peak-time, but also loves to ease you back down to earth and send you off to bed. As a singer-songwriter, he produces melancholic folk music. One thing you can be sure of for Multiverse 2025, Rosemary will deliver variety that will get grinning and moving.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "https://soundcloud.com/mattyrose2",
      OTHER: "",
    },
    {
      "ARTIST NAME": "OOC",
      BIO: "A Dynamic DJ Duo with a flair for the funky and a love of the bass. Expect glitchy electronic goodness from bass house to drum and bass, so fat it would make your mama proud. \n\nHaving performed over the last 12 years in local night clubs and festival main stages, including Party In The Paddock, Great Escape, Falls Festival Marion Bay, Highfields Fest and Mona Foma; OOC has perfected the art of dance-floor manipulation. \n\nOOC released their debut single, ‘Back On The Bus (feat. Hugo Bladel) back in 2019 and has since been homing in on their sound design and signature sounds, preparing to share a new era of drum and bass with the world. Bringing live musical attributes and world class turntablism to their performance forefront, OOC has set their wheels in perpetual motion.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://www.facebook.com/Outofcontextofficial",
      INSTAGRAM: "https://www.instagram.com/oocmusic",
      SOUNDCLOUD: "",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Sam Price",
      BIO: "Influenced by the sounds from Berlin to Belgrade, Sam Price's sound reflects a deep respect for the origins of techno, while constantly pushing boundaries and exploring new dimensions. \n\nIn 2015, Sam Price co-founded Technobrats, a collective that quickly became synonymous with cutting-edge sound and production, with an underground ethos. ",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Scrubrat",
      BIO: "Scrubrat is a step in the direction toward the deeper realms of Drum&Bass, Garage and Deep Dubstep. Every sound is a raw but tastefully creative journey, whether it be original productions or DJ sets. Minimal percussion & simple yet effective basslines are the bread and butter to his sound, as well as being heavily influenced by organic elements & instruments. Sneaking and scampering out of the cracks by night, the rat will compile a journey through the realms of time and bass for all deep heads to enjoy.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "https://soundcloud.com/scrubrataus",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Smoley",
      BIO: "Smoley is the alias of Hobart-based DJ, Emma Smolej. She has quickly established herself as a prominent figure in Hobart's club and bar scene, while also gracing the stages of outdoor parties and festivals including Party in the Paddock, Synergy, Multiverse and Re:Pulse. Known for the seamless flow of her sets, Smoley takes listeners on a captivating journey that keeps them engaged and satisfied, yet always wanting more. Moving seamlessly through the melodic, electronic sounds of House, Techno and Bass Music, she delivers a tightly woven listening experience for anyone to dance to. As Smoley continues to extend her mark, beyond the shores of Tasmania's electronic music scene, her reputation for providing unforgettable sets only grows stronger.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://www.facebook.com/profile.php?id=100064275330390",
      INSTAGRAM: "",
      SOUNDCLOUD: "https://soundcloud.com/djsmoley",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Vøid",
      BIO: "VØID is the atmospheric bass project of Cal Baker. Blending emotive soundscapes with complex bass design and technical drum breaks, a VØID set seeks to present the work of those pushing the boundaries of electronic music production in journeys stretching across the spectrum of human emotion.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://www.facebook.com/VOIDmusicofficial",
      INSTAGRAM: "https://www.instagram.com/void__bass/",
      SOUNDCLOUD: "https://on.soundcloud.com/TF4jE",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Wud",
      BIO: "wud is the alias of lutruwita/Tassie born DJ, Liam Wood.\n\nWith over 7 years playing around the state, Liam has had the chance to play many sets across many styles and genres. He has a strong love for numerous types of electronic music across, and being a man of the north, Techno holds a very special place in his heart.\n\nHaving met many lifelong friends and spending countless (un)forgettable nights on dancefloors over the years, creating similar atmospheres for other punters is what he’s all about.\n\nExpect groovy, dark and bouncy tunes from your friendly neighbourhood wud.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "",
      SOUNDCLOUD: "https://soundcloud.com/wud_33",
      OTHER: "",
    },

    {
      "ARTIST NAME": "Hypnagog",
      BIO: "Hypnagog is a musical project of Felix Fractal aka Terrafractyl and Mental Extensions.\n\nAfter years of writing Psychedelic dance music and experimenting with plenty of other sonic forms, Felix started to spend more time listening to downtempo, psychedelic breaks, IDM and the like. It was time to combine these styles with his own to create some kind of hybrid, beat driven, yet melodic sound. As the project has progressed, Felix has also been experimenting with a kind of jazzy progressive trance and has been working to combine these 2 styles into what could maybe be described as Psychedelic ProgStep. As always, his music is hard to describe and difficult to put into boxes and has been surprising and exhilarating audiences around the world for the past couple of years.\n\nHe has released two EP's on UP records , 'Dreaming in Pieces' (2009) and 'Gyroscopic Bebop'(2010) , and in 2012 another EP, 'Infinite Vibrations' on Adapted records. Most Recently, Felix released the debut Hypnagog album, 'Thematic Mathematics', on his own label Kinematic Records. This album represents the last 3 years of Felix's Hypnagogical experimentation, all wrapped up and woven into an intricate and very unique 80 minutes of sonic vibrations.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://www.facebook.com/Terrafractyl",
      INSTAGRAM: "",
      SOUNDCLOUD: "https://soundcloud.com/hypnagog",
      OTHER: "",
    },
    {
      "ARTIST NAME": "RVNKNG",
      BIO: "RVNKNG (FKA Milquebarth) navigates the cute, dark, and uncertain realms of underground music culture. His debut LP, I'll figure it out, released through RKS Records, reflects a fascination with hidden spaces and the anonymity they oJer. Influenced by artists like Toma Kami, Joey Beltram, DJ Nobu, Venetian Snares, and MCR-T, RVNKNG's DJ sets focus on unpredictability and a playful embrace of uncertainty",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "",
      INSTAGRAM: "https://www.instagram.com/r_k_s_records/",
      SOUNDCLOUD: "https://soundcloud.com/ecb-mixtapes/rvnkng-speed-run",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Stompsy",
      BIO: "StomPsy is the Psychedelic Trance Project of Sean Crole, a established DJ, producer & Co label boss of Tarkine Records based in Tasmania, Australia.\n\nFrom an early age his passion for live music was no secret, attending gigs and outdoor festivals was a frequent occurrence. He first discovered Psytrance at a small outdoor party where Ace Venture Played an unforgettable 3 hour set. He has always been intrigued and inspired by the music industry, and psytrance allowed him to share this passion with others.\n\nSince his move to Hobart in 2015, Stompsy has become a regular fixture in the Psychedelic scene playing at some of the biggest parties across Australia. StomPsys sets can be described as a hybrid blend of Forest, Night Full on and Dark Psy, which results in high energy, floor stomping night time vibes fit for any punter.\n\nHaving released on labels such as Tarkine Records, Sangoma Records and Project 1 music. StomPsy has plenty of original music to get you in the mood to party the night away.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://www.facebook.com/StomPsy",
      INSTAGRAM: "https://www.instagram.com/stompsy_aus/",
      SOUNDCLOUD: "https://soundcloud.com/stompsy",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Allan Pillai",
      BIO: "Those across the Tasmanian Techno scene would all have witnessed one of Allan's sets at a club night, or festival.\n\nAllan is a core part of the SPICYMUSIC crew, and has supported some of the world elite including Anetha, Setoac Mass, Perc, Dasha Rush, Marcel Fengler, Henning Baer, and many more.\n\nWith a run of recent productions on labels such as Olympian, Gynoid and Counter Pulse and a long-standing history of other productions on both international and national labels, Allan has continued to refine, and push the boundaries as an artist and producer.\n\nHe can warm up a night with an eclectic selection of tunes, or bring an infectious and rolling energy to close out the night.",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://www.facebook.com/allanpillaimusic",
      INSTAGRAM: "https://www.instagram.com/allanpmusic_/",
      SOUNDCLOUD: "https://soundcloud.com/allan-pillai",
      OTHER: "",
    },
    {
      "ARTIST NAME": "Delix",
      BIO: "Delix (Del-ix) is the brainchild of Australian born electronic producer Daniel Bower. With over a decade of musical experience playing piano, guitar and brass instruments Delix has focused his creativity on electronic music production since 2017 and has quickly become a formidable presence behind the decks performing explosive and dynamic sets throughout Australia.\n\nDelix‚Äôs debut release Palawa was released on Australian label Sensory Glitch in 2019 and has since released on labels such as Techgnosis Records, Frisson Records and Project:01 Music showcasing a variety of musical genres ranging from Psychedelic Trance, Techno/House and Dub.\n\nReleases On\n\n- Sensory Glitch Records (Aus)\n- Techgnosis Records (Can)\n- Frisson Records (Aus)\n- Subtrail (India)\n- Shadow Wulf Records (USA)\n- Puzzle Records (Aus)",
      "ARTWORK COMPLETED": "YES",
      FACEBOOK: "https://www.facebook.com/dan.delix",
      INSTAGRAM: "https://www.instagram.com/delixandfottip/",
      SOUNDCLOUD: "https://soundcloud.com/delix-140650195",
      OTHER: "",
    },
  ].sort((a, b) => a["ARTIST NAME"].localeCompare(b["ARTIST NAME"])),
};
